import { TokenMarketData, Image } from 'state/nftMarket/types'

export enum PaymentCurrency {
  BNB,
  WBNB,
}

export enum LockStage {
  CREATE_PROTOCOL,
  UPDATE_BADGE_ID,
  UPDATE_TOKEN_ID,
  UPDATE_DEV_TOKEN_ID,
  UNLOCK_BOUNTY,
  UPDATE_PROFILE_ID,
  MINT,
  BURN,
  PARTNER,
  BUY_ACCOUNT,
  UPDATE_ADMIN,
  UPDATE_DEV,
  UPDATE_BLACKLIST,
  ADD_EXTRA_TOKEN,
  REMOVE_EXTRA_TOKEN,
  SPONSOR_TAG,
  UPDATE_SPONSOR_MEDIA,
  CONFIRM_UPDATE_SPONSOR_MEDIA,
  CONFIRM_SPONSOR_TAG,
  CONFIRM_CLAIM_SPONSOR_REVENUE,
  CONFIRM_REMOVE_EXTRA_TOKEN,
  CONFIRM_ADD_EXTRA_TOKEN,
  CONFIRM_UPDATE_BLACKLIST,
  UPDATE_INDIVIDUAL_PROTOCOL,
  CONFIRM_UPDATE_INDIVIDUAL_PROTOCOL,
  CONFIRM_UPDATE_ADMIN,
  CONFIRM_UPDATE_DEV,
  BUY_RAMP,
  INIT_RAMP,
  UPDATE_TRUST,
  UPDATE_BOUNTY,
  UPDATE_OWNER,
  CLAIM,
  PRE_MINT,
  UPDATE_PARAMETERS,
  CLAIM_REVENUE,
  CONFIRM_INIT_RAMP,
  CONFIRM_UNLOCK_BOUNTY,
  CONFIRM_UPDATE_PROFILE_ID,
  CONFIRM_UPDATE_TOKEN_ID,
  CONFIRM_UPDATE_DEV_TOKEN_ID,
  CONFIRM_UPDATE_BADGE_ID,
  CONFIRM_CLAIM_REVENUE,
  CONFIRM_UPDATE_PARAMETERS,
  CONFIRM_CLAIM,
  CONFIRM_UPDATE_OWNER,
  CONFIRM_MINT,
  CONFIRM_BURN,
  CONFIRM_PARTNER,
  CONFIRM_BUY_ACCOUNT,
  CONFIRM_BUY_RAMP,
  CONFIRM_UPDATE_TRUST,
  CONFIRM_UPDATE_BOUNTY,
  CONFIRM_CREATE_PROTOCOL,
  ADMIN_WITHDRAW,
  UPDATE_PROTOCOL,
  UPDATE_COSIGN,
  CONFIRM_UPDATE_COSIGN,
  CONFIRM_UPDATE_PROTOCOL,
  CONFIRM_ADMIN_WITHDRAW,
  DELETE,
  DELETE_RAMP,
  COSIGNS,
  CONFIRM_DELETE,
  CONFIRM_DELETE_RAMP,
  CONFIRM_COSIGNS,
  SETTINGS,
  ADMIN_SETTINGS,
  TX_CONFIRMED,
}

export interface BuyNFT {
  collection: {
    address: string
    name: string
  }
  token: TokenMarketData
  name: string
  image: Image
}
