import { TokenMarketData, Image } from 'state/cancan/types'

export enum LockStage {
  ADMIN_SETTINGS,
  SETTINGS,
  FOLLOW,
  PAY,
  CREATE,
  UPDATE_LATE_DAYS,
  UNFOLLOW,
  ADD_ACCOUNT,
  ADD_ACCOUNT_FROM_PROOF,
  UPDATE_COLLECTION_ID,
  UPDATE_SSID,
  UPDATE_BOUNTY,
  DELETE,
  UPDATE_BADGE_ID,
  UPDATE_BLACKLIST,
  BROADCAST,
  ADD_ACCOUNT2,
  CLAIM_REVENUE,
  REMOVE_ACCOUNT,
  CONFIRM_FOLLOW,
  CONFIRM_CREATE,
  CONFIRM_PAY,
  CONFIRM_UPDATE_LATE_DAYS,
  CONFIRM_UNFOLLOW,
  CONFIRM_ADD_ACCOUNT,
  CONFIRM_ADD_ACCOUNT2,
  CONFIRM_UPDATE_BOUNTY,
  CONFIRM_ADD_ACCOUNT_FROM_PROOF,
  CONFIRM_UPDATE_COLLECTION_ID,
  CONFIRM_UPDATE_SSID,
  CONFIRM_DELETE,
  CONFIRM_UPDATE_BADGE_ID,
  CONFIRM_UPDATE_BLACKLIST,
  CONFIRM_BROADCAST,
  CONFIRM_CLAIM_REVENUE,
  CONFIRM_REMOVE_ACCOUNT,
  TX_CONFIRMED,
  CONFIRM_VOTE_UP,
  CONFIRM_VOTE_DOWN,
  APPROVE_AND_CONFIRM,
  CONFIRM,
}

export interface BuyNFT {
  collection: {
    address: string
    name: string
  }
  token: TokenMarketData
  name: string
  image: Image
}
